# Generated by Django 3.2.7 on 2021-10-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(blank=True, db_column='MAL_ID', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('score', models.TextField(blank=True, db_column='Score', null=True)),
                ('genres', models.TextField(blank=True, db_column='Genres', null=True)),
                ('english_name', models.TextField(blank=True, db_column='English name', null=True)),
                ('japanese_name', models.TextField(blank=True, db_column='Japanese name', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('episodes', models.TextField(blank=True, db_column='Episodes', null=True)),
                ('aired', models.TextField(blank=True, db_column='Aired', null=True)),
                ('premiered', models.TextField(blank=True, db_column='Premiered', null=True)),
                ('producers', models.TextField(blank=True, db_column='Producers', null=True)),
                ('licensors', models.TextField(blank=True, db_column='Licensors', null=True)),
                ('studios', models.TextField(blank=True, db_column='Studios', null=True)),
                ('source', models.TextField(blank=True, db_column='Source', null=True)),
                ('duration', models.TextField(blank=True, db_column='Duration', null=True)),
                ('rating', models.TextField(blank=True, db_column='Rating', null=True)),
                ('ranked', models.TextField(blank=True, db_column='Ranked', null=True)),
                ('popularity', models.IntegerField(blank=True, db_column='Popularity', null=True)),
                ('members', models.IntegerField(blank=True, db_column='Members', null=True)),
                ('favorites', models.IntegerField(blank=True, db_column='Favorites', null=True)),
                ('watching', models.IntegerField(blank=True, db_column='Watching', null=True)),
                ('completed', models.IntegerField(blank=True, db_column='Completed', null=True)),
                ('on_hold', models.IntegerField(blank=True, db_column='On-Hold', null=True)),
                ('dropped', models.IntegerField(blank=True, db_column='Dropped', null=True)),
                ('plan_to_watch', models.IntegerField(blank=True, db_column='Plan to Watch', null=True)),
                ('score_10', models.TextField(blank=True, db_column='Score-10', null=True)),
                ('score_9', models.TextField(blank=True, db_column='Score-9', null=True)),
                ('score_8', models.TextField(blank=True, db_column='Score-8', null=True)),
                ('score_7', models.TextField(blank=True, db_column='Score-7', null=True)),
                ('score_6', models.TextField(blank=True, db_column='Score-6', null=True)),
                ('score_5', models.TextField(blank=True, db_column='Score-5', null=True)),
                ('score_4', models.TextField(blank=True, db_column='Score-4', null=True)),
                ('score_3', models.TextField(blank=True, db_column='Score-3', null=True)),
                ('score_2', models.TextField(blank=True, db_column='Score-2', null=True)),
                ('score_1', models.TextField(blank=True, db_column='Score-1', null=True)),
            ],
            options={
                'db_table': 'anime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimeWithSynopsis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(blank=True, db_column='MAL_ID', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('score', models.TextField(blank=True, db_column='Score', null=True)),
                ('genres', models.TextField(blank=True, db_column='Genres', null=True)),
                ('sypnopsis', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anime_with_synopsis',
                'managed': False,
            },
        ),
    ]
